---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for SQS queue

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  QueueName:
    Type: String
    Description: Name of the SQS queue
    MinLength: 1
    MaxLength: 80
    AllowedPattern: ^[a-zA-Z0-9_-]+$
    ConstraintDescription: Queue name must be alphanumeric, can contain hyphens and underscores

Outputs:
  QueueArn:
    Description: ARN of the SQS queue
    Value: !GetAtt HttpEventsQueue.Arn

  QueueUrl:
    Description: URL of the SQS queue
    Value: !Ref HttpEventsQueue

  QueueName:
    Description: Name of the SQS queue
    Value: !GetAtt HttpEventsQueue.QueueName

Resources:
  HttpEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      VisibilityTimeout: 300
      MessageRetentionPeriod: 300
      ReceiveMessageWaitTimeSeconds: 0
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Ref QueueName


  HttpEventsQueueUrlParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/sqs/${ProjectName}/queue-url"
      Type: "String"
      Value: !Ref HttpEventsQueue
      Description: "URL of the SQS queue"

  HttpEventsQueueArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/sqs/${ProjectName}/queue-arn"
      Type: "String"
      Value: !GetAtt HttpEventsQueue.Arn
      Description: "ARN of the SQS queue"
